# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HW26' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HW26
pod 'Kingfisher', '~> 4.0'
end
