# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HW35' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HW35


pod 'ShimmerSwift'

end
